name = "tg-proxy-2"
main = "src/index.js"
compatibility_date = "2023-10-16"

# A second proxy for load balancing Telegram downloads

[vars]
# TELEGRAM_BOT_TOKEN is set via wrangler secret put

[[kv_namespaces]]
binding = "FILE_CACHE"
# Reusing the same KV namespace for caching file_id -> file_path
id = "bcda6844249d4c4a862c04f3ba21d77f"
